# Generated by Django 4.2.7 on 2025-11-29 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('connect', 'Connect'), ('disconnect', 'Disconnect'), ('import', 'Import'), ('export', 'Export')], max_length=20, verbose_name='Action Type')),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('person', 'Person'), ('trust', 'Trust'), ('group', 'Group'), ('note', 'Note'), ('connection', 'Connection'), ('chart', 'Entire Chart')], max_length=20, verbose_name='Entity Type')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='Entity ID')),
                ('changes', models.JSONField(default=dict, help_text='Detailed information about what was changed', verbose_name='Changes')),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Actor IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chart Audit Log',
                'verbose_name_plural': 'Chart Audit Logs',
                'db_table': 'chart_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartEntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_id', models.CharField(max_length=100, verbose_name='Entity ID')),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('person', 'Person'), ('trust', 'Trust'), ('group', 'Group')], max_length=20, verbose_name='Entity Type')),
                ('link_type', models.CharField(choices=[('tax_docs', 'Tax Documents'), ('licensing', 'Licensing'), ('payments', 'Payments'), ('contracts', 'Contracts'), ('documents', 'Documents')], max_length=20, verbose_name='Link Type')),
                ('target_id', models.CharField(help_text='ID of the linked resource in the target system', max_length=100, verbose_name='Target ID')),
                ('title', models.CharField(max_length=255, verbose_name='Link Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chart Entity Link',
                'verbose_name_plural': 'Chart Entity Links',
                'db_table': 'chart_entity_links',
                'ordering': ['entity_type', 'entity_id', 'link_type'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_id', models.CharField(max_length=100, verbose_name='Entity ID')),
                ('license_type', models.CharField(max_length=100, verbose_name='License Type')),
                ('license_number', models.CharField(max_length=100, verbose_name='License Number')),
                ('issuing_authority', models.CharField(max_length=255, verbose_name='Issuing Authority')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='Renewal Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('pending', 'Pending Renewal')], default='active', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('restrictions', models.TextField(blank=True, verbose_name='Restrictions')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'licenses',
                'ordering': ['expiration_date', 'entity_id'],
            },
        ),
        migrations.CreateModel(
            name='OrgChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.JSONField(default=dict, help_text='Structured JSON containing companies, persons, trusts, groups, and notes', verbose_name='Chart Data')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organizational Chart',
                'verbose_name_plural': 'Organizational Charts',
                'db_table': 'org_charts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_id', models.CharField(max_length=100, verbose_name='Entity ID')),
                ('payment_type', models.CharField(choices=[('invoice', 'Invoice Payment'), ('recurring', 'Recurring Payment'), ('tax', 'Tax Payment'), ('license_fee', 'License Fee'), ('other', 'Other Payment')], max_length=50, verbose_name='Payment Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Invoice Number')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'db_table': 'payment_records',
                'ordering': ['-payment_date', 'entity_id'],
            },
        ),
        migrations.CreateModel(
            name='TaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_id', models.CharField(max_length=100, verbose_name='Entity ID')),
                ('entity_type', models.CharField(default='company', max_length=20, verbose_name='Entity Type')),
                ('document_type', models.CharField(choices=[('corporate_tax', 'Corporate Tax Return'), ('sales_tax', 'Sales Tax Return'), ('payroll_tax', 'Payroll Tax Return'), ('property_tax', 'Property Tax Statement'), ('other', 'Other Tax Document')], max_length=50, verbose_name='Document Type')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('tax_year', models.PositiveIntegerField(verbose_name='Tax Year')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='Filing Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('amended', 'Amended')], default='draft', max_length=20, verbose_name='Status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Document',
                'verbose_name_plural': 'Tax Documents',
                'db_table': 'tax_documents',
                'ordering': ['-tax_year', '-filing_date'],
            },
        ),
    ]
