# Generated by Django 4.2.7 on 2025-11-29 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('charts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='taxdocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_documents', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='orgchart',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='orgchart',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_chart', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='license',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='license',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='chartentitylink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='chartentitylink',
            name='org_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='charts.orgchart', verbose_name='Organizational Chart'),
        ),
        migrations.AddField(
            model_name='chartauditlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AddField(
            model_name='chartauditlog',
            name='org_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='charts.orgchart', verbose_name='Organizational Chart'),
        ),
        migrations.AddIndex(
            model_name='taxdocument',
            index=models.Index(fields=['organization', 'entity_id'], name='tax_documen_organiz_66de0c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxdocument',
            index=models.Index(fields=['tax_year', 'status'], name='tax_documen_tax_yea_84502d_idx'),
        ),
        migrations.AddIndex(
            model_name='taxdocument',
            index=models.Index(fields=['uuid'], name='tax_documen_uuid_bc79cd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['organization', 'entity_id'], name='payment_rec_organiz_3f937c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['payment_type', 'status'], name='payment_rec_payment_403427_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['payment_date'], name='payment_rec_payment_5f9f20_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['uuid'], name='payment_rec_uuid_22726b_idx'),
        ),
        migrations.AddIndex(
            model_name='orgchart',
            index=models.Index(fields=['organization'], name='org_charts_organiz_936c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='orgchart',
            index=models.Index(fields=['uuid'], name='org_charts_uuid_9ce7de_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['organization', 'entity_id'], name='licenses_organiz_5778bb_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_type', 'status'], name='licenses_license_4284a5_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['expiration_date'], name='licenses_expirat_d1da69_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['uuid'], name='licenses_uuid_c2d8fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('organization', 'entity_id', 'license_number')},
        ),
        migrations.AddIndex(
            model_name='chartentitylink',
            index=models.Index(fields=['org_chart', 'entity_id'], name='chart_entit_org_cha_ea2ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='chartentitylink',
            index=models.Index(fields=['link_type', 'target_id'], name='chart_entit_link_ty_646b59_idx'),
        ),
        migrations.AddIndex(
            model_name='chartentitylink',
            index=models.Index(fields=['uuid'], name='chart_entit_uuid_6c13fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chartentitylink',
            unique_together={('org_chart', 'entity_id', 'link_type', 'target_id')},
        ),
        migrations.AddIndex(
            model_name='chartauditlog',
            index=models.Index(fields=['org_chart', 'created_at'], name='chart_audit_org_cha_59d78a_idx'),
        ),
        migrations.AddIndex(
            model_name='chartauditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='chart_audit_entity__06aa2a_idx'),
        ),
        migrations.AddIndex(
            model_name='chartauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='chart_audit_actor_i_1859c9_idx'),
        ),
        migrations.AddIndex(
            model_name='chartauditlog',
            index=models.Index(fields=['uuid'], name='chart_audit_uuid_1bbd9e_idx'),
        ),
    ]
