# Generated by Django 4.2.7 on 2025-11-29 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Identifier')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('org_admin', 'Organization Administrator'), ('org_user', 'Organization User')], default='org_user', max_length=20, verbose_name='User Role')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('identity_provider', models.CharField(choices=[('email', 'Email + Password'), ('google', 'Google OAuth'), ('microsoft', 'Microsoft OAuth')], default='email', max_length=20, verbose_name='Identity Provider')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Phone Verified')),
                ('phone_verification_code', models.CharField(blank=True, max_length=6, verbose_name='Phone Verification Code')),
                ('phone_verification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Phone Verification Sent At')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('email_verification_token', models.CharField(blank=True, max_length=100, verbose_name='Email Verification Token')),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Verification Sent At')),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Password Changed At')),
                ('password_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Password Expires At')),
                ('previous_passwords', models.JSONField(blank=True, default=list, help_text='Stores hashes of previous passwords to prevent reuse', verbose_name='Previous Passwords Hashes')),
                ('password_reset_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Password Reset Token')),
                ('password_reset_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Password Reset Sent At')),
                ('mfa_enabled', models.BooleanField(default=False, verbose_name='MFA Enabled')),
                ('mfa_method', models.CharField(choices=[('totp', 'TOTP (Google Authenticator)'), ('email', 'Email OTP'), ('sms', 'SMS OTP')], default='totp', max_length=20, verbose_name='MFA Method')),
                ('mfa_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='MFA Secret')),
                ('mfa_backup_codes', models.JSONField(blank=True, default=list, help_text='Encrypted backup codes for MFA recovery', verbose_name='MFA Backup Codes')),
                ('mfa_setup_completed', models.BooleanField(default=False, verbose_name='MFA Setup Completed')),
                ('security_level', models.IntegerField(choices=[(1, 'Basic'), (2, 'Standard'), (3, 'Enhanced'), (4, 'Strict')], default=1, verbose_name='Security Level')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Locked Until')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('current_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Current Login IP')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('session_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Session Expiry')),
                ('concurrent_sessions', models.PositiveIntegerField(default=3, verbose_name='Max Concurrent Sessions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Deactivated At')),
                ('deactivation_reason', models.TextField(blank=True, verbose_name='Deactivation Reason')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Must Change Password')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Terms Accepted')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Terms Accepted At')),
                ('privacy_policy_accepted', models.BooleanField(default=False, verbose_name='Privacy Policy Accepted')),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Privacy Policy Accepted At')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20, verbose_name='Date Format')),
                ('notification_settings', models.JSONField(blank=True, default=dict, verbose_name='Notification Preferences')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_users', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organization', verbose_name='Organization')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='users_email_a7cfd1_idx'), models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'), models.Index(fields=['organization', 'is_active'], name='users_organiz_f36d9e_idx'), models.Index(fields=['email_verification_token'], name='users_email_v_9c78de_idx'), models.Index(fields=['password_reset_token'], name='users_passwor_dda668_idx'), models.Index(fields=['uuid'], name='users_uuid_4cb658_idx'), models.Index(fields=['last_activity'], name='users_last_ac_a9fd4f_idx'), models.Index(fields=['locked_until'], name='users_locked__615cd3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='unique_active_email'),
        ),
    ]
