# Generated by Django 4.2.7 on 2025-11-29 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='llmquota',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_quota', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddIndex(
            model_name='llmprovider',
            index=models.Index(fields=['provider_type', 'is_active'], name='llm_provide_provide_cb520f_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprovider',
            index=models.Index(fields=['is_default'], name='llm_provide_is_defa_b6c979_idx'),
        ),
        migrations.AddIndex(
            model_name='llmprovider',
            index=models.Index(fields=['uuid'], name='llm_provide_uuid_03172f_idx'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llm.llmprovider', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='llmanalytics',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_analytics', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddIndex(
            model_name='llmusage',
            index=models.Index(fields=['organization', 'created_at'], name='llm_usage_organiz_027a53_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusage',
            index=models.Index(fields=['user', 'feature'], name='llm_usage_user_id_7e66ce_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusage',
            index=models.Index(fields=['provider', 'model'], name='llm_usage_provide_669561_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusage',
            index=models.Index(fields=['feature', 'status'], name='llm_usage_feature_5b79fa_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusage',
            index=models.Index(fields=['contract'], name='llm_usage_contrac_6ff6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusage',
            index=models.Index(fields=['created_at'], name='llm_usage_created_3feaff_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusage',
            index=models.Index(fields=['uuid'], name='llm_usage_uuid_ae7e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='llmquota',
            index=models.Index(fields=['organization'], name='llm_quotas_organiz_783d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='llmquota',
            index=models.Index(fields=['next_reset_at'], name='llm_quotas_next_re_da7b72_idx'),
        ),
        migrations.AddIndex(
            model_name='llmquota',
            index=models.Index(fields=['is_suspended'], name='llm_quotas_is_susp_4619a8_idx'),
        ),
        migrations.AddIndex(
            model_name='llmquota',
            index=models.Index(fields=['uuid'], name='llm_quotas_uuid_7a5e03_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['provider', 'is_active'], name='llm_models_provide_717372_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['model_type'], name='llm_models_model_t_ea659b_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['is_default'], name='llm_models_is_defa_a793c0_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['uuid'], name='llm_models_uuid_0cb670_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='llmmodel',
            unique_together={('provider', 'name')},
        ),
        migrations.AddIndex(
            model_name='llmanalytics',
            index=models.Index(fields=['organization', 'period_end'], name='llm_analyti_organiz_637a21_idx'),
        ),
        migrations.AddIndex(
            model_name='llmanalytics',
            index=models.Index(fields=['period_type', 'period_end'], name='llm_analyti_period__2a6fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='llmanalytics',
            index=models.Index(fields=['uuid'], name='llm_analyti_uuid_54f3bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='llmanalytics',
            unique_together={('organization', 'period_start', 'period_end', 'period_type')},
        ),
    ]
