# Generated by Django 4.2.7 on 2025-11-29 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20, unique=True, verbose_name='Tier')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly Price (USD)')),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, help_text='20% discount applied if provided', max_digits=10, null=True, verbose_name='Annual Price (USD)')),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Null means unlimited', null=True, verbose_name='Maximum Users')),
                ('max_entities', models.PositiveIntegerField(blank=True, help_text='Null means unlimited', null=True, verbose_name='Maximum Chart Entities')),
                ('max_contracts_per_month', models.PositiveIntegerField(blank=True, help_text='Null means unlimited', null=True, verbose_name='Maximum Contracts/Month')),
                ('monthly_llm_tokens', models.PositiveBigIntegerField(default=0, verbose_name='Monthly LLM Tokens')),
                ('external_signing', models.BooleanField(default=False, verbose_name='External Signing')),
                ('pdf_upload', models.BooleanField(default=False, verbose_name='PDF Upload')),
                ('authoritative_sources', models.BooleanField(default=False, verbose_name='All Authoritative Sources')),
                ('api_access', models.BooleanField(default=False, verbose_name='API Access')),
                ('custom_workflows', models.BooleanField(default=False, verbose_name='Custom Workflows')),
                ('support_level', models.CharField(choices=[('community', 'Community Support'), ('standard', 'Standard Support'), ('priority', 'Priority Support'), ('dedicated', 'Dedicated Support')], default='community', max_length=20, verbose_name='Support Level')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Feature List')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'ordering': ['monthly_price'],
                'indexes': [models.Index(fields=['tier', 'is_active'], name='subscriptio_tier_8542f6_idx'), models.Index(fields=['uuid'], name='subscriptio_uuid_28f51c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10, verbose_name='Billing Cycle')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Trial End Date')),
                ('current_period_start', models.DateTimeField(verbose_name='Current Period Start')),
                ('current_period_end', models.DateTimeField(verbose_name='Current Period End')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('users_count', models.PositiveIntegerField(default=0, verbose_name='Current Users Count')),
                ('entities_count', models.PositiveIntegerField(default=0, verbose_name='Current Entities Count')),
                ('contracts_used_this_month', models.PositiveIntegerField(default=0, verbose_name='Contracts Used This Month')),
                ('llm_tokens_used_this_month', models.PositiveBigIntegerField(default=0, verbose_name='LLM Tokens Used This Month')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization', verbose_name='Organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan', verbose_name='Subscription Plan')),
            ],
            options={
                'verbose_name': 'Organization Subscription',
                'verbose_name_plural': 'Organization Subscriptions',
                'db_table': 'organization_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], default='draft', max_length=20, verbose_name='Status')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Due')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invoice Date')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('line_items', models.JSONField(default=list, verbose_name='Line Items')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization', verbose_name='Organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.organizationsubscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='BillingWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('processor', models.CharField(max_length=50, verbose_name='Payment Processor')),
                ('event_type', models.CharField(max_length=100, verbose_name='Event Type')),
                ('event_id', models.CharField(max_length=100, verbose_name='Event ID')),
                ('payload', models.JSONField(verbose_name='Webhook Payload')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('processing_error', models.TextField(blank=True, verbose_name='Processing Error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
            ],
            options={
                'verbose_name': 'Billing Webhook',
                'verbose_name_plural': 'Billing Webhooks',
                'db_table': 'billing_webhooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['processor', 'event_type'], name='billing_web_process_4813ef_idx'), models.Index(fields=['processed'], name='billing_web_process_1a1a42_idx'), models.Index(fields=['created_at'], name='billing_web_created_0cd6ff_idx'), models.Index(fields=['uuid'], name='billing_web_uuid_a72818_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('method_type', models.CharField(choices=[('card', 'Credit Card'), ('bank', 'Bank Transfer'), ('paypal', 'PayPal'), ('manual', 'Manual Payment')], max_length=20, verbose_name='Method Type')),
                ('last_four', models.CharField(blank=True, max_length=4, verbose_name='Last Four Digits')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Card/Bank Brand')),
                ('expiry_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='Expiry Month')),
                ('expiry_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Expiry Year')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Method')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('provider_id', models.CharField(blank=True, max_length=100, verbose_name='Provider ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', 'created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='payment_met_organiz_fcdfad_idx'), models.Index(fields=['method_type'], name='payment_met_method__c0df5d_idx'), models.Index(fields=['uuid'], name='payment_met_uuid_3d57ef_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_1af930_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['current_period_end'], name='organizatio_current_27561c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status'], name='organizatio_status_ed28b0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['uuid'], name='organizatio_uuid_8474e1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='invoices_organiz_9b03bf_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_due_dat_039a25_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['uuid'], name='invoices_uuid_4abd68_idx'),
        ),
    ]
