# Generated by Django 4.2.7 on 2025-11-29 18:34

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Contract Title')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Contract Number')),
                ('content', models.TextField(verbose_name='Contract Content')),
                ('final_content', models.TextField(blank=True, verbose_name='Final Signed Content')),
                ('original_pdf', models.FileField(blank=True, null=True, upload_to='contracts/original/', verbose_name='Original PDF')),
                ('pdf_overlay_schema', models.JSONField(blank=True, default=dict, help_text='Field positions and metadata for PDF overlays', verbose_name='PDF Overlay Schema')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('completed', 'Completed'), ('expired', 'Expired'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Contract Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('llm_usage_count', models.PositiveIntegerField(default=0, verbose_name='LLM Usage Count')),
                ('last_llm_usage', models.DateTimeField(blank=True, null=True, verbose_name='Last LLM Usage')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent for Signature'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('completed', 'Completed'), ('expired', 'Expired'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('modified', 'Modified'), ('ai_generated', 'AI Generated'), ('ai_edited', 'AI Edited')], max_length=20, verbose_name='Event Type')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Event Metadata')),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Actor IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contract Event',
                'verbose_name_plural': 'Contract Events',
                'db_table': 'contract_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('party_type', models.CharField(choices=[('internal', 'Internal Party'), ('external', 'External Party')], max_length=20, verbose_name='Party Type')),
                ('name', models.CharField(max_length=255, verbose_name='Party Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('org_chart_entity', models.JSONField(blank=True, default=dict, help_text='Reference to organization chart entity', verbose_name='Org Chart Entity')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('role', models.CharField(max_length=100, verbose_name='Role in Contract')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Signed At')),
                ('signing_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Signing IP')),
            ],
            options={
                'verbose_name': 'Contract Party',
                'verbose_name_plural': 'Contract Parties',
                'db_table': 'contract_parties',
                'ordering': ['party_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('standard', 'Standard Contract'), ('nda', 'Non-Disclosure Agreement'), ('employment', 'Employment Agreement'), ('service', 'Service Agreement'), ('partnership', 'Partnership Agreement'), ('custom', 'Custom Template')], default='standard', max_length=20, verbose_name='Template Type')),
                ('content', models.TextField(verbose_name='Template Content')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('placeholders', models.JSONField(blank=True, default=list, help_text='List of placeholder fields in the template', verbose_name='Placeholders')),
                ('signature_blocks', models.JSONField(blank=True, default=list, help_text='Configuration for signature blocks', verbose_name='Signature Blocks')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Template',
                'verbose_name_plural': 'Contract Templates',
                'db_table': 'contract_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('initial', 'Initial'), ('date', 'Date'), ('text', 'Text'), ('checkbox', 'Checkbox')], default='signature', max_length=20, verbose_name='Field Type')),
                ('label', models.CharField(max_length=255, verbose_name='Field Label')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('page_number', models.PositiveIntegerField(default=1, verbose_name='Page Number')),
                ('x_position', models.FloatField(verbose_name='X Position')),
                ('y_position', models.FloatField(verbose_name='Y Position')),
                ('width', models.FloatField(default=200, verbose_name='Width')),
                ('height', models.FloatField(default=50, verbose_name='Height')),
                ('signing_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Signing Token')),
                ('signed_data', encrypted_model_fields.fields.EncryptedTextField(blank=True, verbose_name='Signed Data')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Signed At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_fields', to='contracts.contractparty', verbose_name='Assigned To')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_fields', to='contracts.contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Signature Field',
                'verbose_name_plural': 'Signature Fields',
                'db_table': 'signature_fields',
                'ordering': ['page_number', 'y_position', 'x_position'],
            },
        ),
        migrations.CreateModel(
            name='LegalReferenceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(max_length=100, verbose_name='State/Jurisdiction')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('citation', models.CharField(blank=True, max_length=200, verbose_name='Citation')),
                ('url', models.URLField(verbose_name='Source URL')),
                ('content_type', models.CharField(choices=[('statute', 'Statute'), ('regulation', 'Regulation'), ('case_law', 'Case Law'), ('guideline', 'Guideline'), ('form', 'Standard Form')], default='statute', max_length=20, verbose_name='Content Type')),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('text', 'Text'), ('portal', 'Web Portal')], default='html', max_length=10, verbose_name='Format')),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of relevant topics: formation, operating_agreements, etc.', verbose_name='Topics')),
                ('excerpt', models.TextField(blank=True, verbose_name='Content Excerpt')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Effective Date')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legal Reference',
                'verbose_name_plural': 'Legal References',
                'db_table': 'legal_references',
                'ordering': ['state', 'title'],
                'indexes': [models.Index(fields=['state', 'content_type'], name='legal_refer_state_6cd7e1_idx'), models.Index(fields=['topics'], name='legal_refer_topics_3979fe_idx'), models.Index(fields=['uuid'], name='legal_refer_uuid_c18ae3_idx')],
            },
        ),
    ]
