# Generated by Django 4.2.7 on 2025-11-29 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='contracts.contract', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='internal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Internal User'),
        ),
        migrations.AddField(
            model_name='contractevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AddField(
            model_name='contractevent',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contracts.contract', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='organizations.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contracts', to='contracts.contracttemplate', verbose_name='Source Template'),
        ),
        migrations.AddIndex(
            model_name='signaturefield',
            index=models.Index(fields=['contract', 'assigned_to'], name='signature_f_contrac_1738ef_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturefield',
            index=models.Index(fields=['signing_token'], name='signature_f_signing_86ae24_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturefield',
            index=models.Index(fields=['uuid'], name='signature_f_uuid_2d65a9_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['organization', 'is_active'], name='contract_te_organiz_efc849_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['template_type'], name='contract_te_templat_6ffd80_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['uuid'], name='contract_te_uuid_77b71e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contracttemplate',
            unique_together={('organization', 'name', 'version')},
        ),
        migrations.AddIndex(
            model_name='contractparty',
            index=models.Index(fields=['contract', 'party_type'], name='contract_pa_contrac_3d4604_idx'),
        ),
        migrations.AddIndex(
            model_name='contractparty',
            index=models.Index(fields=['email'], name='contract_pa_email_22c91c_idx'),
        ),
        migrations.AddIndex(
            model_name='contractparty',
            index=models.Index(fields=['uuid'], name='contract_pa_uuid_dc5b29_idx'),
        ),
        migrations.AddIndex(
            model_name='contractevent',
            index=models.Index(fields=['contract', 'event_type'], name='contract_ev_contrac_70f4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='contractevent',
            index=models.Index(fields=['created_at'], name='contract_ev_created_9ede6e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractevent',
            index=models.Index(fields=['uuid'], name='contract_ev_uuid_bebb90_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'status'], name='contracts_organiz_2d8534_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='contracts_contrac_bb0c23_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'expires_at'], name='contracts_status_61d878_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['uuid'], name='contracts_uuid_60ea0b_idx'),
        ),
    ]
