# Generated by Django 4.2.7 on 2025-11-29 18:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Subscription Tier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Legal Name')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industry')),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Primary Contact Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('address_line_1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact_type', models.CharField(choices=[('primary', 'Primary Contact'), ('billing', 'Billing Contact'), ('legal', 'Legal Contact'), ('technical', 'Technical Contact')], max_length=20, verbose_name='Contact Type')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization Contact',
                'verbose_name_plural': 'Organization Contacts',
                'db_table': 'organization_contacts',
                'ordering': ['contact_type', 'last_name', 'first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['subscription_tier', 'is_active'], name='organizatio_subscri_bd60c9_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_at'], name='organizatio_created_8a4b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['uuid'], name='organizatio_uuid_a020d7_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcontact',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_e4fad4_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcontact',
            index=models.Index(fields=['email'], name='organizatio_email_8ae4ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationcontact',
            unique_together={('organization', 'contact_type')},
        ),
    ]
